### PR TITLE
Add LocalVimRCEdit command

### PR DESCRIPTION
**Pull request by blueyed**
This allows for easy editing of the current lvimrc file(s).

### CODE REVIEW

**Comment by embear** [comment]
Thanks for the addition. Some comments here:
  * It would be nice if the user is prompted which file should be edited if there had been more than one sourced.
  * The file `doc/localvimrc.txt` is generated from `README.md` using html2vimdoc (http://github.com/xolox/vim-tools.git). Because of this the documentation needs to be added to `README.md` instead.
  * Changing the length of lines would require to change html2vimdoc. Is it really important to change the length of rulers?

**Comment by blueyed** [comment]
> It would be nice if the user is prompted which file should be edited if there had been more than one sourced.

It edits the first one, and adds the others to the local arglist (now), so you can edit them using e.g. `:next`.

Will move it to the README later - got distracted with installing html2vimdoc.

> Is it really important to change the length of rulers?

Not really.  I've reverted it for now.
Might be worth fixing this in html2vimdoc then later.

**Comment by embear** [comment]
Thanks for the implementation of LocalVimRCEdit. I'll merge the pull request as it is right now, but I will change some things afterwards:

  * use a buffer local variable for each buffer that holds the sourced files
  * provide a dialog to choose which file should be opened.

**Comment by embear** [comment]
What is your opinion on the last commit b181463?

**Pull request merged**
