### PR TITLE
Add option to disable upward search

### LINKED ISSUE #51: How do I disable searching lvimrc in the file tree?
**Case 1**
I have a `.lvimrc` in root of my project `~/project/.lvimrc`. I open Vim from root of the project and the plugin loads the file. Which is the perfect behaviour.

**Case 2**
On the other hand, if I change directory to `~/project/child/` and open Vim there. The plugin searches upward and finds and load `.lvimrc` file.

In case 2, I want to disable searching upward. I want plugin to search just in the current directory. How do I disable "search upward through the file tree" feature of the plugin?

Thank you

### PR DESCRIPTION
**Pull request by talha131**
This option is disabled by default.

Close #51

### CODE REVIEW

**Comment by embear** [comment]
Hi Talha,

thank you for your contribution! Currently I'm not really sure if I like the patch in the current form.
I totally agree that it might be useful to disable searching the directory tree. But I'm not sure if it is correct/common sense to use the directory of the file currently edited. Maybe it is also an good option to use the current working directory only. Or possibly both of the directories.

**Comment by talha131** [comment]
@embear I understand your point and I agree with you.

**Correct me if I am wrong**, the patch only searches in the directory of the current file. It should also search in the current working directory i.e. `:pwd`.

I will try to add this in near future and resubmit this PR.

**Comment by talha131** [comment]
@embear I have updated the PR and have tried my best to address your concern.

Kindly review and merge if acceptable.

**Comment by embear** [comment]
Sorry for the late reply. I was on a business trip and had no time to review in depth until now. But I thougth about the above discussion.
When I think about it again it is not a good idea to search in the `:pwd` (nevertheless the patch doesn't do this). The idea behind localvimrc is to source project specific settings from the project tree. When vim is started from an arbitrary directory possibly outside of the project tree it might have strange and none obvious effects.
I've take your ideas from the first pull request but implemented them in the same way as the other options in localvimrc were implemented (script local variables). I hope this is the same functionality you had in mind. Please see 476e0ea29cfbe8cdfa88f7099f814fd477935ddc
Possibly the changeset aaea27fe897edbfb0c5f71ef0ac02489f4bcfefa is also interesting for you to finish sourcing of files ....

**Comment by talha131** [comment]
@embear I am closing this PR. Though currently I can't read your fix or test if it actually fixes the issue #51 that started it all, due to time constraints. I will get back to you later if I have any feedback or question.

Thanks for your time.

**Pull request closed without merging**
