### PR TITLE
Some fixes.

### PR DESCRIPTION
**Pull request by clin18**
Feel free to reject 964c197 if you disagree. There should be little controversy with the other 3.

### CODE REVIEW

**Comment by embear** [comment]
20a8698d7612d92b006c43c7137d58a5f58018d0:
Implemented slightly different in commit e3468006816ca90af5126b65492335ed1fcc5677

39d5cfc962cb05aaf747dbecc0a15fa154eeef64:
This patch makes sourcing work for some files but does not work for paths containing spaces. Any patch that makes sourcing for paths containing any characters like `\?*+#'"§$%&/ ()=` work are welcome. 

5f66b04d6203fe4bcc2e2af4cad920153cee9854:
Merged

964c197af25877e8bb6611bdec85c2d1849ba37d:
I will not merge this. You can change theses setting using the vimrc setting `g:localvimrc_event`. The default of `BufWinEnter` had been chosen because this was buffer and window local settings will be set for each opened split.

**Comment by clin18** [comment]
Updated 39d5cfc with 6aaec1e. Verified that the crazy path works.

**Comment by embear** [comment]
Sorry, still not working correctly here:
```
mkdir -p '/tmp/foo/bar\baz'
echo "echom 'in /tmp/foo'" > '/tmp/foo/.lvimrc'
echo "echom 'in /tmp/foo/bar\baz'" > '/tmp/foo/bar\baz/.lvimrc'
vi '/tmp/foo/bar\baz/qux'
```
If you turn on debugging using `let g:localvimrc_debug = 99` you get following. No .lvimrc is sourced ...
```
localvimrc: ==================================================
localvimrc: localvimrc.vim 1
localvimrc: unable to read persistence file '/lhome/braun5m/.vim/localvimrc'
localvimrc: searching directory "/tmp/foo/bar\\baz"
localvimrc: found files: []
localvimrc: candidate files: []
localvimrc: ==================================================
```
Using ` ` (space) instead of `\`
```
mkdir -p '/tmp/foo/bar baz'
echo "echom 'in /tmp/foo'" > '/tmp/foo/.lvimrc'
echo "echom 'in /tmp/foo/bar baz'" > '/tmp/foo/bar baz/.lvimrc'
vi '/tmp/foo/bar baz/qux'
```
you get the correct behaviour
```
localvimrc: ==================================================
localvimrc: localvimrc.vim 1
localvimrc: unable to read persistence file '/lhome/braun5m/.vim/localvimrc'
localvimrc: searching directory "/tmp/foo/bar\ baz"
localvimrc: found files: ['/tmp/.lvimrc', '/tmp/foo/.lvimrc', '/tmp/foo/bar baz/.lvimrc']
localvimrc: candidate files: ['/tmp/.lvimrc', '/tmp/foo/.lvimrc', '/tmp/foo/bar baz/.lvimrc']
localvimrc: processing "/tmp/.lvimrc"
localvimrc: stored information: answer = '' sandbox answer = '' checksum = ''
localvimrc: checksum calc -> /tmp/.lvimrc : 32rw-r--r--1443683183
localvimrc: checksum mismatch, no answer reuse
localvimrc: g:localvimrc_file = /tmp/foo/bar baz/qux, g:localvimrc_file_dir = /tmp/foo/bar baz
localvimrc: g:localvimrc_script = /tmp/.lvimrc, g:localvimrc_script_dir = /tmp
localvimrc: g:localvimrc_sourced_once = 0, g:localvimrc_sourced_once_for_file = 0
foo
localvimrc: sourced /tmp/.lvimrc
localvimrc: checksum calc -> /tmp/.lvimrc : 32rw-r--r--1443683183
localvimrc: processing "/tmp/foo/.lvimrc"
localvimrc: stored information: answer = '' sandbox answer = '' checksum = ''
localvimrc: checksum calc -> /tmp/foo/.lvimrc : 20rw-r--r--1443697793
localvimrc: checksum mismatch, no answer reuse
localvimrc: g:localvimrc_file = /tmp/foo/bar baz/qux, g:localvimrc_file_dir = /tmp/foo/bar baz
localvimrc: g:localvimrc_script = /tmp/foo/.lvimrc, g:localvimrc_script_dir = /tmp/foo
localvimrc: g:localvimrc_sourced_once = 0, g:localvimrc_sourced_once_for_file = 0
in /tmp/foo
localvimrc: sourced /tmp/foo/.lvimrc
localvimrc: checksum calc -> /tmp/foo/.lvimrc : 20rw-r--r--1443697793
localvimrc: processing "/tmp/foo/bar baz/.lvimrc"
localvimrc: stored information: answer = '' sandbox answer = '' checksum = ''
localvimrc: checksum calc -> /tmp/foo/bar\ baz/.lvimrc : 28rw-r--r--1443697793
localvimrc: checksum mismatch, no answer reuse
localvimrc: g:localvimrc_file = /tmp/foo/bar baz/qux, g:localvimrc_file_dir = /tmp/foo/bar baz
localvimrc: g:localvimrc_script = /tmp/foo/bar baz/.lvimrc, g:localvimrc_script_dir = /tmp/foo/bar
baz
localvimrc: g:localvimrc_sourced_once = 0, g:localvimrc_sourced_once_for_file = 0
in /tmp/foo/bar baz
localvimrc: sourced /tmp/foo/bar baz/.lvimrc
localvimrc: checksum calc -> /tmp/foo/bar\ baz/.lvimrc : 28rw-r--r--1443697793
localvimrc: ==================================================
```

**Comment by clin18** [comment]
The change only concerns the checksum now. I don't see how sourcing could be affected. Please make sure you're looking at 6aaec1.

**Comment by clin18** [comment]
Just tested your example with 6aaec1ec8ca34e907342e8a4ba2849d738661245, and it does work for me:

```
localvimrc: ==================================================                                       
localvimrc: localvimrc.vim 1
localvimrc: searching directory "/tmp/foo/bar\ baz"
localvimrc: found files: ['/tmp/foo/.lvimrc', '/tmp/foo/bar baz/.lvimrc']
localvimrc: candidate files: ['/tmp/foo/.lvimrc', '/tmp/foo/bar baz/.lvimrc']
localvimrc: processing "/tmp/foo/.lvimrc"
localvimrc: stored information: answer = '' sandbox answer = '' checksum = ''
localvimrc: checksum calc -> /tmp/foo/.lvimrc : 20rw-r--r--1443751072
localvimrc: checksum mismatch, no answer reuse
localvimrc: need to ask
localvimrc: answer is "y"
localvimrc: g:localvimrc_file = /tmp/foo/bar baz/qux, g:localvimrc_file_dir = /tmp/foo/bar baz
localvimrc: g:localvimrc_script = /tmp/foo/.lvimrc, g:localvimrc_script_dir = /tmp/foo
localvimrc: g:localvimrc_sourced_once = 0, g:localvimrc_sourced_once_for_file = 0
localvimrc: using sandbox
in /tmp/foo
localvimrc: sourced /tmp/foo/.lvimrc
localvimrc: checksum calc -> /tmp/foo/.lvimrc : 20rw-r--r--1443751072
localvimrc: processing "/tmp/foo/bar baz/.lvimrc"
localvimrc: stored information: answer = '' sandbox answer = '' checksum = ''
localvimrc: checksum calc -> /tmp/foo/bar\ baz/.lvimrc : 28rw-r--r--1443751096
localvimrc: checksum mismatch, no answer reuse
localvimrc: need to ask
localvimrc: answer is "y"
localvimrc: g:localvimrc_file = /tmp/foo/bar baz/qux, g:localvimrc_file_dir = /tmp/foo/bar baz
localvimrc: g:localvimrc_script = /tmp/foo/bar baz/.lvimrc, g:localvimrc_script_dir = /tmp/foo/bar baz
localvimrc: g:localvimrc_sourced_once = 0, g:localvimrc_sourced_once_for_file = 0
localvimrc: using sandbox
in /tmp/foo/bar baz
localvimrc: sourced /tmp/foo/bar baz/.lvimrc
localvimrc: checksum calc -> /tmp/foo/bar\ baz/.lvimrc : 28rw-r--r--1443751096
localvimrc: ==================================================
```

Here's your example on e3468006816ca90af5126b65492335ed1fcc5677, notice the -1-1 checksum:

```
localvimrc: ==================================================                                       
localvimrc: localvimrc.vim 1
localvimrc: searching directory "/tmp/foo/bar\ baz"
localvimrc: found files: ['/tmp/foo/.lvimrc', '/tmp/foo/bar baz/.lvimrc']
localvimrc: candidate files: ['/tmp/foo/.lvimrc', '/tmp/foo/bar baz/.lvimrc']
localvimrc: processing "/tmp/foo/.lvimrc"
localvimrc: stored information: answer = '' sandbox answer = '' checksum = ''
localvimrc: checksum calc -> /tmp/foo/.lvimrc : 20rw-r--r--1443751072
localvimrc: checksum mismatch, no answer reuse
localvimrc: need to ask
localvimrc: answer is "y"
localvimrc: g:localvimrc_file = /tmp/foo/bar baz/qux, g:localvimrc_file_dir = /tmp/foo/bar baz
localvimrc: g:localvimrc_script = /tmp/foo/.lvimrc, g:localvimrc_script_dir = /tmp/foo
localvimrc: g:localvimrc_sourced_once = 0, g:localvimrc_sourced_once_for_file = 0
localvimrc: using sandbox
in /tmp/foo
localvimrc: sourced /tmp/foo/.lvimrc
localvimrc: checksum calc -> /tmp/foo/.lvimrc : 20rw-r--r--1443751072
localvimrc: processing "/tmp/foo/bar baz/.lvimrc"
localvimrc: stored information: answer = '' sandbox answer = '' checksum = ''
localvimrc: checksum calc -> /tmp/foo/bar\\\ baz/.lvimrc : -1-1
localvimrc: checksum mismatch, no answer reuse
localvimrc: need to ask
localvimrc: answer is "y"
localvimrc: g:localvimrc_file = /tmp/foo/bar baz/qux, g:localvimrc_file_dir = /tmp/foo/bar baz
localvimrc: g:localvimrc_script = /tmp/foo/bar baz/.lvimrc, g:localvimrc_script_dir = /tmp/foo/bar baz
localvimrc: g:localvimrc_sourced_once = 0, g:localvimrc_sourced_once_for_file = 0
localvimrc: using sandbox
in /tmp/foo/bar baz
localvimrc: sourced /tmp/foo/bar baz/.lvimrc
localvimrc: checksum calc -> /tmp/foo/bar\ baz/.lvimrc : -1-1
localvimrc: ==================================================
```

**Comment by embear** [comment]
I should not do such things in a hurry. No I get the point. I does not work for all paths but fixes checksums for paths containing spaces.

I need to take a look into the general problem of special characters in file names.

**Pull request merged**
